# Generated by Django 3.2.13 on 2022-06-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vwm_master', '0002_auto_20220612_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
